name: my-bank
version: '0.1.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/clone?schema=public
    container_name: nextjs_app
    environment: 
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clone?schema=public
      - NEXT_WEBPACK_USEPOLLING=1
    ports: 
      - '3000:3000'
      - '5555:5555'
    volumes:
      - /app/.next
      - /app/node_moduls
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine
    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOUR_STRONG_PASSWORD
      POSTGRES_DB: clone

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clone"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

 